# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb8a13a21dc8cd7dfb7d3b626aa488d7726812c3e360d549c12b26d1fc533ef9f33a4ac4949ba6c5c5498ee0fb6d554a24609abba5b2ac903d8f9fd2a1bfee6

test:
  secret_key_base: 6638e8fc25003bc6ed0c5fb1514b284cc9b272677e89b07ab961d5105d41e1ac846dfa58da4ffdfb2bb24b0c25e10a2bb0dfc51cfed0a79780e60e215f53e691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
